### PR TITLE
Bug disable cruise control #104

### LINKED ISSUE #104: BUG disable cruise control
Description:
When cruise control is active and methods such as emergencyBrake (smartcar.ino), SlowDownSmoothly (smartcar.ino) and Brake (DriverDashboard.java) are being called, cruise control is not being disabled resulting in an unpleasant driving experience.

### PR DESCRIPTION
**Pull request by ChrisAxt**
fixes #104  , see last commit for changes made.
closes #104 

This bug fix is part of #94

### CODE REVIEW

**Review by alrapal — COMMENTED** [review]
Good catch Chris ! And good fix ! I just have a question down below regarding the new view that is created 😄

File: UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java [hunk 1]
```diff
@@ -202,6 +204,7 @@ public void onCruiseControlBtn(View view) {
         } else {
             drive(IDLE_SPEED, STRAIGHT_ANGLE, "stopping");
         }
+        cruiseControl = view;
```
Comment (alrapal) [inline UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java]: Why do we need to declare a new view here to assign it later on the onClick method and not assign it to the already existing view via the ID ? 🤔

Comment (ChrisAxt) [reply UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java]: > Why do we need to declare a new view here to assign it later on the onClick method and not assign it to the already existing view via the ID ? 🤔

Well I needed the view in order to use the performClick() and couldn't think of another way to do it.

Comment (alrapal) [reply UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java]: It would be something like:
In the onCreate() method :
ToggleButton cruiseControl = findViewById(R.id.cruise_control);

And where you need call
cruiseControl.performClick()
And then you don't need to assign the view in this method. (Which prevents the view to change if another view is using that method)
But you version works also, just concerned if at some point the onClick method for cruise control is used with other views it would create maybe conflicts

Comment (alrapal) [reply UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java]: @gusaxtcha and I agreed that I would make the changes presented above to allow him to work on another task.

**Review by alrapal — APPROVED** [review]

**Review by ediz-genc — APPROVED** [review]
Good timing for the bug :) Good work.
