### PR TITLE
[Bug_Fix] Cruise control affecting steering and throttle uncontrollably

### LINKED ISSUE #102: [BUG] Cruise control affecting steering and throttle uncontrollably
Description: 
When cruise control is active, steering using the thumbstick doesn't work (the steering manoeuvre becomes very wide), and the vehicle unexpectedly goes backwards.

Looking into this and will provide further details

### PR DESCRIPTION
**Pull request by iachella**
fixes #102 via this branch's last commit (see last commit for changes description)
closes #102  

This bug fix is part of #94 

Notes:
All code done by myself and @gusaxtcha

### CODE REVIEW

File: UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java [hunk 1]
```diff
@@ -181,7 +182,7 @@ public void onThumbstickMoved(float xPercent, float yPercent, int id) {
                 //setting fixed speed for cruise control
                 strength = seekProgress;
             } else {
-                strength = (int) (yPercent * seekProgress);
+                strength = (int) (yPercent * -seekProgress);
```
Comment (juliavankirk) [inline UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java:185]: Nice to see this back :)

**Review by juliavankirk — APPROVED** [review]
Looks good, code runs well as intended
